# Generated by Django 5.2.2 on 2025-10-09 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SerenoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de sereno',
                'verbose_name_plural': 'Tipos de serenos',
                'db_table': 'sereno_tipo',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apepaterno', models.CharField(max_length=50)),
                ('apematerno', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(default='00000000', max_length=8, unique=True)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('NO_OPERATIVO', 'No operativo')], default='OPERATIVO', max_length=15)),
                ('tipo', models.ForeignKey(default='Sereno a pie', on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='personal.serenotipo')),
            ],
            options={
                'verbose_name': 'Tipo de persona',
                'verbose_name_plural': 'Tipos de personas',
                'db_table': 'persona',
            },
        ),
    ]
