# Generated by Django 5.2.2 on 2025-07-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apepaterno', models.CharField(max_length=50)),
                ('apematerno', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
