# Generated by Django 5.2.2 on 2025-07-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_rename_incidencia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('DELITO', 'Delito'), ('FALTA', 'Falta'), ('INFRACCION', 'Infracción'), ('OPERATIVO', 'Operativo'), ('APOYO', 'Apoyo')], default='DELITO', max_length=15),
        ),
    ]
